export const ui = {
  avatar: {
    size: '40px',
  },
  border: {
    'radius-lg': '16px',
    'radius-md': '8px',
    'radius-sm': '4px',
  },
  button: {
    'border-outlined': '1px',
    'size-lg': '56px',
    'size-md': '48px',
    'size-sm': '32px',
  },
  flags: {
    lg: '40px',
    md: '32px',
    sm: '24px',
  },
  icon: {
    'button-lg': '48px',
    'button-md': '40px',
    'button-sm': '28px',
    lg: '32px',
    md: '24px',
    sm: '16px',
    xlg: '48px',
  },
  list: {
    'item-desinty-comfortable': '32px',
    'item-desinty-compact': '16px',
    'item-desinty-minimal': '8px',
    'item-desinty-normal': '24px',
    'item-desinty-spacious': '32px',
    'item-padding-border': '16px',
    'item-padding-side': '24px',
  },
  sheet: {
    radius: '24px',
  },
  spaces: {
    '2': '2px',
    '4': '4px',
    '8': '8px',
    '12': '12px',
    '16': '16px',
    '20': '20px',
    '24': '24px',
    '32': '32px',
    '40': '40px',
    '48': '48px',
    '56': '56px',
    '64': '64px',
    '72': '72px',
    '80': '80px',
  },
  tab: {
    height: '56px',
  },
  tag: {
    'border-radius': '4px',
    sm: '20px',
  },
  toast: {
    'min-height': 'spaces.56',
  },
};
export const typography = {
  body: {
    family: 'Roboto',
    'letter-spacing': '0px',
    'md-line-height': '20px',
    'md-size': '16px',
    'sm-line-height': '18px',
    'sm-size': '14px',
    weight: '500',
  },
  button: {
    family: 'Roboto',
    'letter-spacing': '0.25px',
    'lg-line-height': '16px',
    'lg-size': '16px',
    'md-line-height': '16px',
    'md-size': '16px',
    'sm-line-height': '14px',
    'sm-size': '14px',
    weight: '500',
  },
  form: {
    'choiceControl-family': 'Roboto',
    'choiceControl-letter-spacing': '0px',
    'choiceControl-line-height': '24px',
    'choiceControl-selected-weight': 500,
    'choiceControl-size': '16px',
    'choiceControl-unselected-weight': 400,
    'input-family': 'Roboto',
    'input-filled-weight': 500,
    'input-letter-spacing': '0px',
    'input-line-height': '20px',
    'input-placeholder-weight': 400,
    'input-size': '18px',
    'label-family': 'Roboto',
    'label-letter-spacing': '0.25px',
    'label-md-line-height': '20px',
    'label-md-size': '14px',
    'label-weight': 500,
    'swtich-description-line-height': '18px',
    'swtich-description-size': '14px',
    'swtich-description-weight': 400,
    'swtich-family': 'Roboto',
    'swtich-label-line-height': '24px',
    'swtich-label-size': '16px',
    'swtich-label-weight': 500,
    'swtich-letter-spacing': '0px',
  },
  functional: {
    family: 'Roboto',
    'letter-spacing': '0.5px',
    'md-line-height': '18px',
    'md-size': '14px',
    'sm-highlight-weight': 700,
    'sm-line-height': '14px',
    'sm-size': '12px',
    weight: 500,
  },
  hero: {
    family: 'Roboto Display',
    'letter-spacing': '-0.75px',
    'lg-letter-spacing': '0px',
    'lg-line-height': '64px',
    'lg-size': '56px',
    'md-line-height': '56px',
    'md-size': '40px',
    'sm-line-height': '40px',
    'sm-size': '32px',
    weight: 700,
  },
  link: {
    family: 'Roboto',
    'letter-spacing': '0px',
    'md-line-height': '20px',
    'md-size': '16px',
    'sm-line-height': '18px',
    'sm-size': '14px',
    weight: 400,
  },
  list: {
    'content-emphasized': '500px',
    'content-line-height': '20px',
    'content-size': '16px',
    'content-support-line-height': '18px',
    'content-support-size': '14px',
    family: 'Roboto',
    'letter-spacing': '0px',
    weight: 'body.weight',
  },
  onboarding: {
    'web-title-family': 'Roboto',
    'web-title-letter-spacing': '0px',
    'web-title-line-height': '40px',
    'web-title-size': '32px',
    'web-title-weight': 400,
  },
  overline: {
    family: 'Roboto',
    'letter-spacing': '0px',
    'line-height': '12px',
    size: '10px',
    weight: 500,
  },
  subtitle: {
    family: 'Roboto',
    'letter-spacing': '0px',
    'lg-line-height': '32px',
    'lg-size': '24px',
    'md-line-height': '24px',
    'md-size': '18px',
    weight: 500,
  },
  tag: {
    family: 'Roboto',
    'letter-spacing': '0px',
    'line-height': '12px',
    size: '10px',
    weight: 500,
  },
  title: {
    family: 'Roboto',
    'letter-spacing': '0px',
    'lg-line-height': '40px',
    'lg-size': '32px',
    'md-line-height': '32px',
    'md-size': '24px',
    'sm-line-height': '24px',
    'sm-size': '20px',
    weight: 500,
  },
};
